---
- name: Atualizando o sistema operacional
  hosts: linux
  remote_user: suporte
  become: true
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 

- name: Install Softwares Suporte
  hosts: linux
  remote_user: suporte
  become: true
  tasks: 
  - name: Install a list of packages suporte
    ansible.builtin.package:
      pkg:
        - build-essential

  - name: Download file from a file path
    get_url:
      url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      dest: /home/suporte/downloads

  # - name: Install a .deb package from the internet
  #   apt:
  #     deb: https://example.com/python-ppq_0.1-1_all.deb

  - name: Install a .deb package
    apt:
      deb: /home/suporte/downloads/teamviewer_15.27.3_amd64.deb
